### PR TITLE
Add support for Cygwin paths

### PR DESCRIPTION
**Pull request by fracz**
When using [babun](http://babun.github.io/) or [Cygwin](https://www.cygwin.com/), system drives are mapped as `/cygdrive/{DRIVE_LETTER}`. This causes git review fail to find `.gitreview` file in project directory as the Cygwin mapping is not available from system's python installation dir.

This fix looks for `/cygdrive/{LETTER}` in project path and replaces it with `LETTER:/` so git review can properly find the `.gitreview` file.

Without this fix, each call to `git review` from babun or Cygwin results in

```
No '.gitreview' file found in this repository. We don't know where
your gerrit is. Please manually create a remote named "gerrit" and try
again.
```

### CODE REVIEW

**Comment by openstack-gerrit** [comment]
Thank you for contributing to openstack-infra/git-review!

openstack-infra/git-review uses Gerrit for code review.

Please visit
http://docs.openstack.org/infra/manual/developers.html#development-workflow
and follow the instructions there to upload your change to Gerrit.

**Comment by fungi** [comment]
I can repropose this into our code review system, but am curious about the use case. Since git-review runs natively on Windows (from what I hear--I don't have any Windows machines to test with), what reasons might a user actually want to run it under Cygwin instead?

**Comment by fungi** [comment]
Working backwards from the proposed patch, it looks like `git rev-parse` is being run from within the context of Cygwin, but `git review` is run under a system-installed Python... so the goal is to support a workflow which involves Git running via Cygwin but Python running outside Cygwin?

**Comment by fracz** [comment]
I have freshly installed [babun](http://babun.github.io/). I had python installed before. And indeed, `git rev-parse` executed from this console returns path starting from `/cygdrive/c/projects/...`. But the following line in git-review

```py
config = Config(os.path.join(top_dir, ".gitreview"))
```

can not find the file as the `/cygdrive/c/...` does not exists from there. I hardcoded it first to my project's path there, but starting with `C:\projects` and it solved the problem. This led me to the solution I have proposed.

git-review works flawlessly from Windows console - indeed. But there are better solutions (like Cygwin) that facilitates other console-tasks and lot of people use it.

But maybe it is a problem with my installation only.

**Comment by fungi** [comment]
Thanks for the clarification. I find it odd that you don't install Python within Cygwin when running Python-based tools from a Cygwin shell (given that it's an interpreted language). Do you know if this is a common workflow among developers running Windows? It seems like other interpreters (Perl, BASH, PHP and so on) would exhibit similar behavior under those conditions.

**Comment by fracz** [comment]
Ok, you are absolutely right. After I removed my previously installed Python from PATH, the Cygwin's python started to work. All problems with git-review disappeared.

Sorry for bothering you. Hope this thread will help someone in the future with similar problems :-)

**Pull request closed without merging**
